# Generated by Django 4.2.1 on 2023-05-13 09:27

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('title1', models.CharField(max_length=550)),
                ('title2', models.CharField(max_length=550)),
                ('title3', models.CharField(max_length=550)),
                ('title4', models.CharField(max_length=550)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Basicfuctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('title1', models.CharField(max_length=550)),
                ('text1', models.TextField()),
                ('title2', models.CharField(max_length=550)),
                ('text2', models.TextField()),
                ('title3', models.CharField(max_length=550)),
                ('text3', models.TextField()),
                ('title4', models.CharField(max_length=550)),
                ('text4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 10, 27, 48, 565969))),
                ('leadimg', models.ImageField(default='myleadimg.jpg', upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table': 'Blog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=550)),
                ('city', models.CharField(max_length=550)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 10, 27, 48, 565969))),
                ('img', models.ImageField(upload_to='')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Integrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=550)),
                ('text1', models.TextField()),
                ('title2', models.CharField(max_length=550)),
                ('text2', models.TextField()),
                ('title3', models.CharField(max_length=550)),
                ('text3', models.TextField()),
                ('title4', models.CharField(max_length=550)),
                ('text4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Moreinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 10, 27, 48, 565969))),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Moreinfo',
                'verbose_name_plural': 'Moreinfo',
                'db_table': 'Moreinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ourservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('subtext', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('title1', models.CharField(max_length=550)),
                ('img1', models.ImageField(upload_to='')),
                ('title2', models.CharField(max_length=550)),
                ('img2', models.ImageField(upload_to='')),
                ('title3', models.CharField(max_length=550)),
                ('img3', models.ImageField(upload_to='')),
                ('title4', models.CharField(max_length=550)),
                ('img4', models.ImageField(upload_to='')),
                ('title5', models.CharField(max_length=550)),
                ('img5', models.ImageField(upload_to='')),
                ('title6', models.CharField(max_length=550)),
                ('img6', models.ImageField(upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 10, 27, 48, 565969))),
            ],
            options={
                'verbose_name': 'ourservice',
                'verbose_name_plural': 'ourservice',
                'db_table': 'ourservice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ourstory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 10, 27, 48, 565969))),
                ('leadimg', models.ImageField(default='myleadimg.jpg', upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Ourstory',
                'verbose_name_plural': 'Ourstory',
                'db_table': 'Ourstory',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('post', models.CharField(max_length=550)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 10, 27, 48, 565969))),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ourteamtext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('img1', models.ImageField(upload_to='')),
                ('img2', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('number1', models.CharField(max_length=50)),
                ('text1', models.CharField(max_length=50)),
                ('number2', models.CharField(max_length=50)),
                ('text2', models.CharField(max_length=50)),
                ('number3', models.CharField(max_length=50)),
                ('text3', models.CharField(max_length=50)),
                ('number4', models.CharField(max_length=50)),
                ('text4', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Whatwedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Whatweoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=550)),
                ('title', models.CharField(max_length=550)),
                ('firsttext', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 10, 27, 48, 565969))),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Whatweoffer',
                'verbose_name_plural': 'Whatweoffer',
                'db_table': 'Whatweoffer',
                'managed': True,
            },
        ),
    ]
