# Generated by Django 4.2.1 on 2023-05-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatwedo',
            name='Weorking_ability',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='detailed_planning',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='improved_operating_conditions',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='machine_power',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='number1',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='number2',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='number3',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='number4',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='number5',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='quality_services',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 46, 45, 382628)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 46, 45, 367008)),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 46, 45, 367008)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 46, 45, 382628)),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 46, 45, 367008)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 46, 45, 382628)),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 21, 46, 45, 382628)),
        ),
    ]
