# Generated by Django 4.2.1 on 2023-05-15 07:41

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction', '0007_remove_aboutus_title4_alter_blog_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservice',
            name='body',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='title5',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='title6',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204)),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204)),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204)),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204)),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550)),
                ('slug', models.SlugField(blank=True, max_length=550, null=True)),
                ('published', models.BooleanField(blank=True, default=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2023, 5, 15, 8, 41, 14, 235204))),
                ('leadimg', models.ImageField(default='myleadimg.jpg', upload_to='')),
                ('body', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
                'db_table': 'Services',
                'managed': True,
            },
        ),
    ]
