# Generated by Django 4.2.1 on 2023-05-16 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_remove_banner_title_banner_smalltext1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Banner1',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 54, 1, 512483)),
        ),
    ]
