# Generated by Django 4.2.1 on 2023-05-16 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_rename_banner_banner1_alter_blog_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(blank=True, max_length=1000, null=True)),
                ('smalltext1', models.CharField(blank=True, max_length=1000, null=True)),
                ('title2', models.CharField(blank=True, max_length=1000, null=True)),
                ('smalltext2', models.CharField(blank=True, max_length=1000, null=True)),
                ('title3', models.CharField(blank=True, max_length=1000, null=True)),
                ('smalltext3', models.CharField(blank=True, max_length=1000, null=True)),
                ('title4', models.CharField(blank=True, max_length=1000, null=True)),
                ('smalltext4', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner1',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 57, 39, 638880)),
        ),
    ]
