# Generated by Django 4.2.1 on 2023-05-16 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_slider_delete_banner1_alter_blog_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='leadimg',
            field=models.ImageField(blank=True, default='myleadimg.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='moreinfo',
            name='leadimg',
            field=models.ImageField(blank=True, default='myleadimg.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='leadimg',
            field=models.ImageField(blank=True, default='myleadimg.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 906395)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 890810)),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 890810)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 906395)),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 890810)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 906395)),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 906395)),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 18, 45, 30, 906395)),
        ),
    ]
