# Generated by Django 4.2.1 on 2023-05-16 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_aboutus_leadimg_moreinfo_leadimg_whatwedo_leadimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatweoffer',
            name='leadimg',
            field=models.ImageField(blank=True, default='myleadimg.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
        migrations.AlterField(
            model_name='customers',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
        migrations.AlterField(
            model_name='ourservice',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
        migrations.AlterField(
            model_name='ourstory',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
        migrations.AlterField(
            model_name='services',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 19, 18, 0, 71329)),
        ),
    ]
